Handles 856-field.
NatLibFi/melinda-record-import-transformer-onix pull request #43
Opened 2020-11-02 13:25 UTC by natlibesa

2020-11-03 08:12 UTC, natlibfi-arlehiko requested changes

2020-11-03 08:12 UTC, natlibfi-arlehiko commented on src/transform/convert/index.js
>  export default ({source4Value, isLegalDeposit, sources, sender, moment = momentOrig}) => ({Product: record}) => {
Change to `export default ({source4Value, isLegalDeposit, sources, sender, moment = momentOrig}) => async ({Product: record}) => {`

2020-11-03 08:12 UTC, natlibfi-arlehiko commented on src/transform/convert/index.js
> +      generate856(), // <--
Change to `await generate856`

2020-11-03 08:12 UTC, natlibfi-arlehiko commented on src/transform/convert/index.js
> +      function createURN(isbn = false) {
Change to `await function createURN(isbn = false) {`

2020-11-03 08:12 UTC, natlibfi-arlehiko commented on src/transform/convert/index.js
> +              {code: 'u', value: createURN(isbn)},
Change to `{code: 'u', value: await createURN(isbn)},`

2020-11-03 08:12 UTC, natlibfi-arlehiko commented on src/transform/convert/index.js
> +        const response = fetch(URN_GENERATOR_URL);
Change to `const response = await fetch(URN_GENERATOR_URL);`

2020-11-03 08:12 UTC, natlibfi-arlehiko commented on src/transform/convert/index.js
> +        const body = response.text();
Change to `const body = await response.text();`

2020-11-04 09:15 UTC, natlibfi-jonollil commented on src/transform/convert/index.js
> +      await function createURN(isbn = false) {
async function...

2020-11-04 09:19 UTC, natlibfi-jonollil commented on src/transform/convert/index.js
> +      function getIsbn() {
In VScode: File -> Preferences -> Settings -> search: trim -> enable: Trailing-spaces: Trim On Save

2020-12-07 10:55 UTC, natlibfi-jonollil requested changes

2020-12-07 10:55 UTC, natlibfi-jonollil commented on src/transform/convert/generate3XXFields.js
> +
Empty lines clean up. 1 empty between functions and 0 between } }. Groupping up the consts and one emptyline before if makes code more readable

2020-12-14 08:56 UTC, natlibfi-jonollil approved these changes

2020-12-21 08:14 UTC, natlibfi-jonollil approved these changes

2020-12-21 08:15 UTC, merged